### ISSUE TITLE
Bug - Tamaño máximo de la Descripción

### ISSUE THREAD

**Issue by dml1994** [albfree/WauwApp#53]
En la vista Profile veo recomendable establecer un máximo de caracteres para la descripción. (Recomiendo 200).

**Comment by pedroswe** [comment]
Se ha gestionado el tamaño de la descripción de esta manera: 
![image](https://user-images.githubusercontent.com/36974279/79084957-e01e2780-7d36-11ea-842c-9831a32bccbd.png)
